# This Makefile is for the WordNet::Similarity extension to perl.
#
# It was generated automatically by MakeMaker version
# 6.57_05 (Revision: 65705) from the contents of
# Makefile.PL. Don't edit this file, edit Makefile.PL instead.
#
#       ANY CHANGES MADE HERE WILL BE LOST!
#
#   MakeMaker ARGV: ()
#

#   MakeMaker Parameters:

#     ABSTRACT_FROM => q[lib/WordNet/Similarity.pm]
#     AUTHOR => [q[Ted Pedersen, Siddharth Patwardhan, Satanjeev Banerjee, Jason Michelizzi]]
#     BUILD_REQUIRES => {  }
#     CONFIGURE => CODE(...)
#     EXE_FILES => [q[utils/BNCFreq.pl], q[utils/brownFreq.pl], q[utils/compounds.pl], q[utils/rawtextFreq.pl], q[utils/semCorRawFreq.pl], q[utils/semCorFreq.pl], q[utils/similarity.pl], q[utils/treebankFreq.pl], q[utils/wordVectors.pl], q[utils/wnDepths.pl], q[utils/similarity_server.pl]]
#     LICENSE => q[gpl]
#     NAME => q[WordNet::Similarity]
#     NO_META => q[true]
#     PL_FILES => { build/Depthfiles.PL=>q[$(INST_LIB)/WordNet/synsetdepths.dat], build/Infocontent.PL=>q[$(INST_LIB)/WordNet/ic-semcor.dat] }
#     PREREQ_PM => { Getopt::Long=>q[0], WordNet::QueryData=>q[1.40], Digest::SHA1=>q[0], File::Spec=>q[0], CGI=>q[0], File::Find=>q[0], IO=>q[0], File::Temp=>q[0], Text::Similarity=>q[0.02] }
#     VERSION_FROM => q[lib/WordNet/Similarity.pm]
#     dist => { COMPRESS=>q[gzip -9f], SUFFIX=>q[gz] }
#     realclean => { FILES=>q[build/wnpath.txt] }

#   MakeMaker 'CONFIGURE' Parameters:

# no values returned

# --- MakeMaker post_initialize section:


# --- MakeMaker const_config section:

# These definitions are from config.sh (via /usr/lib/perl/5.14/Config.pm).
# They may have been overridden via Makefile.PL or on the command line.
AR = ar
CC = cc
CCCDLFLAGS = -fPIC
CCDLFLAGS = -Wl,-E
DLEXT = so
DLSRC = dl_dlopen.xs
EXE_EXT = 
FULL_AR = /usr/bin/ar
LD = cc
LDDLFLAGS = -shared -O2 -g -L/usr/local/lib -fstack-protector
LDFLAGS =  -fstack-protector -L/usr/local/lib
LIBC = 
LIB_EXT = .a
OBJ_EXT = .o
OSNAME = linux
OSVERS = 2.6.24-31-server
RANLIB = :
SITELIBEXP = /usr/local/share/perl/5.14.2
SITEARCHEXP = /usr/local/lib/perl/5.14.2
SO = so
VENDORARCHEXP = /usr/lib/perl5
VENDORLIBEXP = /usr/share/perl5


# --- MakeMaker constants section:
AR_STATIC_ARGS = cr
DIRFILESEP = /
DFSEP = $(DIRFILESEP)
NAME = WordNet::Similarity
NAME_SYM = WordNet_Similarity
VERSION = 2.05
VERSION_MACRO = VERSION
VERSION_SYM = 2_05
DEFINE_VERSION = -D$(VERSION_MACRO)=\"$(VERSION)\"
XS_VERSION = 2.05
XS_VERSION_MACRO = XS_VERSION
XS_DEFINE_VERSION = -D$(XS_VERSION_MACRO)=\"$(XS_VERSION)\"
INST_ARCHLIB = blib/arch
INST_SCRIPT = blib/script
INST_BIN = blib/bin
INST_LIB = blib/lib
INST_MAN1DIR = blib/man1
INST_MAN3DIR = blib/man3
MAN1EXT = 1p
MAN3EXT = 3pm
INSTALLDIRS = site
DESTDIR = 
PREFIX = /usr
PERLPREFIX = $(PREFIX)
SITEPREFIX = $(PREFIX)/local
VENDORPREFIX = $(PREFIX)
INSTALLPRIVLIB = $(PERLPREFIX)/share/perl/5.14
DESTINSTALLPRIVLIB = $(DESTDIR)$(INSTALLPRIVLIB)
INSTALLSITELIB = $(SITEPREFIX)/share/perl/5.14.2
DESTINSTALLSITELIB = $(DESTDIR)$(INSTALLSITELIB)
INSTALLVENDORLIB = $(VENDORPREFIX)/share/perl5
DESTINSTALLVENDORLIB = $(DESTDIR)$(INSTALLVENDORLIB)
INSTALLARCHLIB = $(PERLPREFIX)/lib/perl/5.14
DESTINSTALLARCHLIB = $(DESTDIR)$(INSTALLARCHLIB)
INSTALLSITEARCH = $(SITEPREFIX)/lib/perl/5.14.2
DESTINSTALLSITEARCH = $(DESTDIR)$(INSTALLSITEARCH)
INSTALLVENDORARCH = $(VENDORPREFIX)/lib/perl5
DESTINSTALLVENDORARCH = $(DESTDIR)$(INSTALLVENDORARCH)
INSTALLBIN = $(PERLPREFIX)/bin
DESTINSTALLBIN = $(DESTDIR)$(INSTALLBIN)
INSTALLSITEBIN = $(SITEPREFIX)/bin
DESTINSTALLSITEBIN = $(DESTDIR)$(INSTALLSITEBIN)
INSTALLVENDORBIN = $(VENDORPREFIX)/bin
DESTINSTALLVENDORBIN = $(DESTDIR)$(INSTALLVENDORBIN)
INSTALLSCRIPT = $(PERLPREFIX)/bin
DESTINSTALLSCRIPT = $(DESTDIR)$(INSTALLSCRIPT)
INSTALLSITESCRIPT = $(SITEPREFIX)/bin
DESTINSTALLSITESCRIPT = $(DESTDIR)$(INSTALLSITESCRIPT)
INSTALLVENDORSCRIPT = $(VENDORPREFIX)/bin
DESTINSTALLVENDORSCRIPT = $(DESTDIR)$(INSTALLVENDORSCRIPT)
INSTALLMAN1DIR = $(PERLPREFIX)/share/man/man1
DESTINSTALLMAN1DIR = $(DESTDIR)$(INSTALLMAN1DIR)
INSTALLSITEMAN1DIR = $(SITEPREFIX)/man/man1
DESTINSTALLSITEMAN1DIR = $(DESTDIR)$(INSTALLSITEMAN1DIR)
INSTALLVENDORMAN1DIR = $(VENDORPREFIX)/share/man/man1
DESTINSTALLVENDORMAN1DIR = $(DESTDIR)$(INSTALLVENDORMAN1DIR)
INSTALLMAN3DIR = $(PERLPREFIX)/share/man/man3
DESTINSTALLMAN3DIR = $(DESTDIR)$(INSTALLMAN3DIR)
INSTALLSITEMAN3DIR = $(SITEPREFIX)/man/man3
DESTINSTALLSITEMAN3DIR = $(DESTDIR)$(INSTALLSITEMAN3DIR)
INSTALLVENDORMAN3DIR = $(VENDORPREFIX)/share/man/man3
DESTINSTALLVENDORMAN3DIR = $(DESTDIR)$(INSTALLVENDORMAN3DIR)
PERL_LIB = /usr/share/perl/5.14
PERL_ARCHLIB = /usr/lib/perl/5.14
LIBPERL_A = libperl.a
FIRST_MAKEFILE = Makefile
MAKEFILE_OLD = Makefile.old
MAKE_APERL_FILE = Makefile.aperl
PERLMAINCC = $(CC)
PERL_INC = /usr/lib/perl/5.14/CORE
PERL = /usr/bin/perl
FULLPERL = /usr/bin/perl
ABSPERL = $(PERL)
PERLRUN = $(PERL)
FULLPERLRUN = $(FULLPERL)
ABSPERLRUN = $(ABSPERL)
PERLRUNINST = $(PERLRUN) "-I$(INST_ARCHLIB)" "-I$(INST_LIB)"
FULLPERLRUNINST = $(FULLPERLRUN) "-I$(INST_ARCHLIB)" "-I$(INST_LIB)"
ABSPERLRUNINST = $(ABSPERLRUN) "-I$(INST_ARCHLIB)" "-I$(INST_LIB)"
PERL_CORE = 0
PERM_DIR = 755
PERM_RW = 644
PERM_RWX = 755

MAKEMAKER   = /usr/share/perl/5.14/ExtUtils/MakeMaker.pm
MM_VERSION  = 6.57_05
MM_REVISION = 65705

# FULLEXT = Pathname for extension directory (eg Foo/Bar/Oracle).
# BASEEXT = Basename part of FULLEXT. May be just equal FULLEXT. (eg Oracle)
# PARENT_NAME = NAME without BASEEXT and no trailing :: (eg Foo::Bar)
# DLBASE  = Basename part of dynamic library. May be just equal BASEEXT.
MAKE = make
FULLEXT = WordNet/Similarity
BASEEXT = Similarity
PARENT_NAME = WordNet
DLBASE = $(BASEEXT)
VERSION_FROM = lib/WordNet/Similarity.pm
OBJECT = 
LDFROM = $(OBJECT)
LINKTYPE = dynamic
BOOTDEP = 

# Handy lists of source code files:
XS_FILES = 
C_FILES  = 
O_FILES  = 
H_FILES  = 
MAN1PODS = utils/BNCFreq.pl \
	utils/brownFreq.pl \
	utils/compounds.pl \
	utils/rawtextFreq.pl \
	utils/semCorFreq.pl \
	utils/semCorRawFreq.pl \
	utils/similarity.pl \
	utils/similarity_server.pl \
	utils/treebankFreq.pl \
	utils/wnDepths.pl \
	utils/wordVectors.pl
MAN3PODS = lib/WordNet/Similarity.pm \
	lib/WordNet/Similarity/DepthFinder.pm \
	lib/WordNet/Similarity/FrequencyCounter.pm \
	lib/WordNet/Similarity/GlossFinder.pm \
	lib/WordNet/Similarity/ICFinder.pm \
	lib/WordNet/Similarity/PathFinder.pm \
	lib/WordNet/Similarity/hso.pm \
	lib/WordNet/Similarity/jcn.pm \
	lib/WordNet/Similarity/lch.pm \
	lib/WordNet/Similarity/lesk.pm \
	lib/WordNet/Similarity/lin.pm \
	lib/WordNet/Similarity/path.pm \
	lib/WordNet/Similarity/random.pm \
	lib/WordNet/Similarity/res.pm \
	lib/WordNet/Similarity/vector.pm \
	lib/WordNet/Similarity/vector_pairs.pm \
	lib/WordNet/Similarity/wup.pm \
	lib/WordNet/Tools.pm \
	lib/WordNet/get_wn_info.pm \
	lib/WordNet/stem.pm \
	lib/WordNet/vectorFile.pm

# Where is the Config information that we are using/depend on
CONFIGDEP = $(PERL_ARCHLIB)$(DFSEP)Config.pm $(PERL_INC)$(DFSEP)config.h

# Where to build things
INST_LIBDIR      = $(INST_LIB)/WordNet
INST_ARCHLIBDIR  = $(INST_ARCHLIB)/WordNet

INST_AUTODIR     = $(INST_LIB)/auto/$(FULLEXT)
INST_ARCHAUTODIR = $(INST_ARCHLIB)/auto/$(FULLEXT)

INST_STATIC      = 
INST_DYNAMIC     = 
INST_BOOT        = 

# Extra linker info
EXPORT_LIST        = 
PERL_ARCHIVE       = 
PERL_ARCHIVE_AFTER = 


TO_INST_PM = lib/WordNet/Similarity.pm \
	lib/WordNet/Similarity/DepthFinder.pm \
	lib/WordNet/Similarity/FrequencyCounter.pm \
	lib/WordNet/Similarity/GlossFinder.pm \
	lib/WordNet/Similarity/ICFinder.pm \
	lib/WordNet/Similarity/PathFinder.pm \
	lib/WordNet/Similarity/hso.pm \
	lib/WordNet/Similarity/jcn.pm \
	lib/WordNet/Similarity/lch.pm \
	lib/WordNet/Similarity/lesk.pm \
	lib/WordNet/Similarity/lin.pm \
	lib/WordNet/Similarity/path.pm \
	lib/WordNet/Similarity/random.pm \
	lib/WordNet/Similarity/res.pm \
	lib/WordNet/Similarity/vector.pm \
	lib/WordNet/Similarity/vector_pairs.pm \
	lib/WordNet/Similarity/wup.pm \
	lib/WordNet/Tools.pm \
	lib/WordNet/get_wn_info.pm \
	lib/WordNet/lesk-relation.dat \
	lib/WordNet/stem.pm \
	lib/WordNet/vector-pairs-relation.dat \
	lib/WordNet/vector-relation.dat \
	lib/WordNet/vectorFile.pm \
	lib/WordNet/wordvectors.dat

PM_TO_BLIB = lib/WordNet/Similarity/vector_pairs.pm \
	blib/lib/WordNet/Similarity/vector_pairs.pm \
	lib/WordNet/Similarity.pm \
	blib/lib/WordNet/Similarity.pm \
	lib/WordNet/lesk-relation.dat \
	blib/lib/WordNet/lesk-relation.dat \
	lib/WordNet/Similarity/hso.pm \
	blib/lib/WordNet/Similarity/hso.pm \
	lib/WordNet/wordvectors.dat \
	blib/lib/WordNet/wordvectors.dat \
	lib/WordNet/Similarity/random.pm \
	blib/lib/WordNet/Similarity/random.pm \
	lib/WordNet/Tools.pm \
	blib/lib/WordNet/Tools.pm \
	lib/WordNet/Similarity/PathFinder.pm \
	blib/lib/WordNet/Similarity/PathFinder.pm \
	lib/WordNet/Similarity/lesk.pm \
	blib/lib/WordNet/Similarity/lesk.pm \
	lib/WordNet/Similarity/DepthFinder.pm \
	blib/lib/WordNet/Similarity/DepthFinder.pm \
	lib/WordNet/Similarity/lin.pm \
	blib/lib/WordNet/Similarity/lin.pm \
	lib/WordNet/Similarity/ICFinder.pm \
	blib/lib/WordNet/Similarity/ICFinder.pm \
	lib/WordNet/Similarity/path.pm \
	blib/lib/WordNet/Similarity/path.pm \
	lib/WordNet/stem.pm \
	blib/lib/WordNet/stem.pm \
	lib/WordNet/Similarity/jcn.pm \
	blib/lib/WordNet/Similarity/jcn.pm \
	lib/WordNet/Similarity/FrequencyCounter.pm \
	blib/lib/WordNet/Similarity/FrequencyCounter.pm \
	lib/WordNet/Similarity/GlossFinder.pm \
	blib/lib/WordNet/Similarity/GlossFinder.pm \
	lib/WordNet/vectorFile.pm \
	blib/lib/WordNet/vectorFile.pm \
	lib/WordNet/Similarity/lch.pm \
	blib/lib/WordNet/Similarity/lch.pm \
	lib/WordNet/Similarity/vector.pm \
	blib/lib/WordNet/Similarity/vector.pm \
	lib/WordNet/vector-pairs-relation.dat \
	blib/lib/WordNet/vector-pairs-relation.dat \
	lib/WordNet/Similarity/res.pm \
	blib/lib/WordNet/Similarity/res.pm \
	lib/WordNet/vector-relation.dat \
	blib/lib/WordNet/vector-relation.dat \
	lib/WordNet/get_wn_info.pm \
	blib/lib/WordNet/get_wn_info.pm \
	lib/WordNet/Similarity/wup.pm \
	blib/lib/WordNet/Similarity/wup.pm


# --- MakeMaker platform_constants section:
MM_Unix_VERSION = 6.57_05
PERL_MALLOC_DEF = -DPERL_EXTMALLOC_DEF -Dmalloc=Perl_malloc -Dfree=Perl_mfree -Drealloc=Perl_realloc -Dcalloc=Perl_calloc


# --- MakeMaker tool_autosplit section:
# Usage: $(AUTOSPLITFILE) FileToSplit AutoDirToSplitInto
AUTOSPLITFILE = $(ABSPERLRUN)  -e 'use AutoSplit;  autosplit($$ARGV[0], $$ARGV[1], 0, 1, 1)' --



# --- MakeMaker tool_xsubpp section:


# --- MakeMaker tools_other section:
SHELL = /bin/sh
CHMOD = chmod
CP = cp
MV = mv
NOOP = $(TRUE)
NOECHO = @
RM_F = rm -f
RM_RF = rm -rf
TEST_F = test -f
TOUCH = touch
UMASK_NULL = umask 0
DEV_NULL = > /dev/null 2>&1
MKPATH = $(ABSPERLRUN) -MExtUtils::Command -e 'mkpath' --
EQUALIZE_TIMESTAMP = $(ABSPERLRUN) -MExtUtils::Command -e 'eqtime' --
FALSE = false
TRUE = true
ECHO = echo
ECHO_N = echo -n
UNINST = 0
VERBINST = 0
MOD_INSTALL = $(ABSPERLRUN) -MExtUtils::Install -e 'install([ from_to => {@ARGV}, verbose => '\''$(VERBINST)'\'', uninstall_shadows => '\''$(UNINST)'\'', dir_mode => '\''$(PERM_DIR)'\'' ]);' --
DOC_INSTALL = $(ABSPERLRUN) -MExtUtils::Command::MM -e 'perllocal_install' --
UNINSTALL = $(ABSPERLRUN) -MExtUtils::Command::MM -e 'uninstall' --
WARN_IF_OLD_PACKLIST = $(ABSPERLRUN) -MExtUtils::Command::MM -e 'warn_if_old_packlist' --
MACROSTART = 
MACROEND = 
USEMAKEFILE = -f
FIXIN = $(ABSPERLRUN) -MExtUtils::MY -e 'MY->fixin(shift)' --


# --- MakeMaker makemakerdflt section:
makemakerdflt : all
	$(NOECHO) $(NOOP)


# --- MakeMaker dist section:
TAR = tar
TARFLAGS = cvf
ZIP = zip
ZIPFLAGS = -r
COMPRESS = gzip -9f
SUFFIX = gz
SHAR = shar
PREOP = $(NOECHO) $(NOOP)
POSTOP = $(NOECHO) $(NOOP)
TO_UNIX = $(NOECHO) $(NOOP)
CI = ci -u
RCS_LABEL = rcs -Nv$(VERSION_SYM): -q
DIST_CP = best
DIST_DEFAULT = tardist
DISTNAME = WordNet-Similarity
DISTVNAME = WordNet-Similarity-2.05


# --- MakeMaker macro section:


# --- MakeMaker depend section:


# --- MakeMaker cflags section:


# --- MakeMaker const_loadlibs section:


# --- MakeMaker const_cccmd section:


# --- MakeMaker post_constants section:


# --- MakeMaker pasthru section:

PASTHRU = LIBPERL_A="$(LIBPERL_A)"\
	LINKTYPE="$(LINKTYPE)"\
	PREFIX="$(PREFIX)"


# --- MakeMaker special_targets section:
.SUFFIXES : .xs .c .C .cpp .i .s .cxx .cc $(OBJ_EXT)

.PHONY: all config static dynamic test test_all linkext manifest blibdirs clean realclean disttest distdir



# --- MakeMaker c_o section:


# --- MakeMaker xs_c section:


# --- MakeMaker xs_o section:


# --- MakeMaker top_targets section:
all :: pure_all manifypods
	$(NOECHO) $(NOOP)


pure_all :: config pm_to_blib subdirs linkext
	$(NOECHO) $(NOOP)

subdirs :: $(MYEXTLIB)
	$(NOECHO) $(NOOP)

config :: $(FIRST_MAKEFILE) blibdirs
	$(NOECHO) $(NOOP)

help :
	perldoc ExtUtils::MakeMaker


# --- MakeMaker blibdirs section:
blibdirs : $(INST_LIBDIR)$(DFSEP).exists $(INST_ARCHLIB)$(DFSEP).exists $(INST_AUTODIR)$(DFSEP).exists $(INST_ARCHAUTODIR)$(DFSEP).exists $(INST_BIN)$(DFSEP).exists $(INST_SCRIPT)$(DFSEP).exists $(INST_MAN1DIR)$(DFSEP).exists $(INST_MAN3DIR)$(DFSEP).exists
	$(NOECHO) $(NOOP)

# Backwards compat with 6.18 through 6.25
blibdirs.ts : blibdirs
	$(NOECHO) $(NOOP)

$(INST_LIBDIR)$(DFSEP).exists :: Makefile.PL
	$(NOECHO) $(MKPATH) $(INST_LIBDIR)
	$(NOECHO) $(CHMOD) $(PERM_DIR) $(INST_LIBDIR)
	$(NOECHO) $(TOUCH) $(INST_LIBDIR)$(DFSEP).exists

$(INST_ARCHLIB)$(DFSEP).exists :: Makefile.PL
	$(NOECHO) $(MKPATH) $(INST_ARCHLIB)
	$(NOECHO) $(CHMOD) $(PERM_DIR) $(INST_ARCHLIB)
	$(NOECHO) $(TOUCH) $(INST_ARCHLIB)$(DFSEP).exists

$(INST_AUTODIR)$(DFSEP).exists :: Makefile.PL
	$(NOECHO) $(MKPATH) $(INST_AUTODIR)
	$(NOECHO) $(CHMOD) $(PERM_DIR) $(INST_AUTODIR)
	$(NOECHO) $(TOUCH) $(INST_AUTODIR)$(DFSEP).exists

$(INST_ARCHAUTODIR)$(DFSEP).exists :: Makefile.PL
	$(NOECHO) $(MKPATH) $(INST_ARCHAUTODIR)
	$(NOECHO) $(CHMOD) $(PERM_DIR) $(INST_ARCHAUTODIR)
	$(NOECHO) $(TOUCH) $(INST_ARCHAUTODIR)$(DFSEP).exists

$(INST_BIN)$(DFSEP).exists :: Makefile.PL
	$(NOECHO) $(MKPATH) $(INST_BIN)
	$(NOECHO) $(CHMOD) $(PERM_DIR) $(INST_BIN)
	$(NOECHO) $(TOUCH) $(INST_BIN)$(DFSEP).exists

$(INST_SCRIPT)$(DFSEP).exists :: Makefile.PL
	$(NOECHO) $(MKPATH) $(INST_SCRIPT)
	$(NOECHO) $(CHMOD) $(PERM_DIR) $(INST_SCRIPT)
	$(NOECHO) $(TOUCH) $(INST_SCRIPT)$(DFSEP).exists

$(INST_MAN1DIR)$(DFSEP).exists :: Makefile.PL
	$(NOECHO) $(MKPATH) $(INST_MAN1DIR)
	$(NOECHO) $(CHMOD) $(PERM_DIR) $(INST_MAN1DIR)
	$(NOECHO) $(TOUCH) $(INST_MAN1DIR)$(DFSEP).exists

$(INST_MAN3DIR)$(DFSEP).exists :: Makefile.PL
	$(NOECHO) $(MKPATH) $(INST_MAN3DIR)
	$(NOECHO) $(CHMOD) $(PERM_DIR) $(INST_MAN3DIR)
	$(NOECHO) $(TOUCH) $(INST_MAN3DIR)$(DFSEP).exists



# --- MakeMaker linkext section:

linkext :: $(LINKTYPE)
	$(NOECHO) $(NOOP)


# --- MakeMaker dlsyms section:


# --- MakeMaker dynamic section:

dynamic :: $(FIRST_MAKEFILE) $(INST_DYNAMIC) $(INST_BOOT)
	$(NOECHO) $(NOOP)


# --- MakeMaker dynamic_bs section:

BOOTSTRAP =


# --- MakeMaker dynamic_lib section:


# --- MakeMaker static section:

## $(INST_PM) has been moved to the all: target.
## It remains here for awhile to allow for old usage: "make static"
static :: $(FIRST_MAKEFILE) $(INST_STATIC)
	$(NOECHO) $(NOOP)


# --- MakeMaker static_lib section:


# --- MakeMaker manifypods section:

POD2MAN_EXE = $(PERLRUN) "-MExtUtils::Command::MM" -e pod2man "--"
POD2MAN = $(POD2MAN_EXE)


manifypods : pure_all  \
	utils/rawtextFreq.pl \
	utils/BNCFreq.pl \
	utils/similarity.pl \
	utils/wordVectors.pl \
	utils/compounds.pl \
	utils/semCorRawFreq.pl \
	utils/brownFreq.pl \
	utils/similarity_server.pl \
	utils/treebankFreq.pl \
	utils/wnDepths.pl \
	utils/semCorFreq.pl \
	lib/WordNet/Similarity/vector_pairs.pm \
	lib/WordNet/Similarity.pm \
	lib/WordNet/Similarity/hso.pm \
	lib/WordNet/Similarity/random.pm \
	lib/WordNet/Tools.pm \
	lib/WordNet/Similarity/PathFinder.pm \
	lib/WordNet/Similarity/lesk.pm \
	lib/WordNet/Similarity/DepthFinder.pm \
	lib/WordNet/Similarity/lin.pm \
	lib/WordNet/Similarity/ICFinder.pm \
	lib/WordNet/Similarity/path.pm \
	lib/WordNet/stem.pm \
	lib/WordNet/Similarity/jcn.pm \
	lib/WordNet/Similarity/FrequencyCounter.pm \
	lib/WordNet/Similarity/GlossFinder.pm \
	lib/WordNet/vectorFile.pm \
	lib/WordNet/Similarity/lch.pm \
	lib/WordNet/Similarity/vector.pm \
	lib/WordNet/Similarity/res.pm \
	lib/WordNet/get_wn_info.pm \
	lib/WordNet/Similarity/wup.pm
	$(NOECHO) $(POD2MAN) --section=$(MAN1EXT) --perm_rw=$(PERM_RW) \
	  utils/rawtextFreq.pl $(INST_MAN1DIR)/rawtextFreq.pl.$(MAN1EXT) \
	  utils/BNCFreq.pl $(INST_MAN1DIR)/BNCFreq.pl.$(MAN1EXT) \
	  utils/similarity.pl $(INST_MAN1DIR)/similarity.pl.$(MAN1EXT) \
	  utils/wordVectors.pl $(INST_MAN1DIR)/wordVectors.pl.$(MAN1EXT) \
	  utils/compounds.pl $(INST_MAN1DIR)/compounds.pl.$(MAN1EXT) \
	  utils/semCorRawFreq.pl $(INST_MAN1DIR)/semCorRawFreq.pl.$(MAN1EXT) \
	  utils/brownFreq.pl $(INST_MAN1DIR)/brownFreq.pl.$(MAN1EXT) \
	  utils/similarity_server.pl $(INST_MAN1DIR)/similarity_server.pl.$(MAN1EXT) \
	  utils/treebankFreq.pl $(INST_MAN1DIR)/treebankFreq.pl.$(MAN1EXT) \
	  utils/wnDepths.pl $(INST_MAN1DIR)/wnDepths.pl.$(MAN1EXT) \
	  utils/semCorFreq.pl $(INST_MAN1DIR)/semCorFreq.pl.$(MAN1EXT) 
	$(NOECHO) $(POD2MAN) --section=$(MAN3EXT) --perm_rw=$(PERM_RW) \
	  lib/WordNet/Similarity/vector_pairs.pm $(INST_MAN3DIR)/WordNet::Similarity::vector_pairs.$(MAN3EXT) \
	  lib/WordNet/Similarity.pm $(INST_MAN3DIR)/WordNet::Similarity.$(MAN3EXT) \
	  lib/WordNet/Similarity/hso.pm $(INST_MAN3DIR)/WordNet::Similarity::hso.$(MAN3EXT) \
	  lib/WordNet/Similarity/random.pm $(INST_MAN3DIR)/WordNet::Similarity::random.$(MAN3EXT) \
	  lib/WordNet/Tools.pm $(INST_MAN3DIR)/WordNet::Tools.$(MAN3EXT) \
	  lib/WordNet/Similarity/PathFinder.pm $(INST_MAN3DIR)/WordNet::Similarity::PathFinder.$(MAN3EXT) \
	  lib/WordNet/Similarity/lesk.pm $(INST_MAN3DIR)/WordNet::Similarity::lesk.$(MAN3EXT) \
	  lib/WordNet/Similarity/DepthFinder.pm $(INST_MAN3DIR)/WordNet::Similarity::DepthFinder.$(MAN3EXT) \
	  lib/WordNet/Similarity/lin.pm $(INST_MAN3DIR)/WordNet::Similarity::lin.$(MAN3EXT) \
	  lib/WordNet/Similarity/ICFinder.pm $(INST_MAN3DIR)/WordNet::Similarity::ICFinder.$(MAN3EXT) \
	  lib/WordNet/Similarity/path.pm $(INST_MAN3DIR)/WordNet::Similarity::path.$(MAN3EXT) \
	  lib/WordNet/stem.pm $(INST_MAN3DIR)/WordNet::stem.$(MAN3EXT) \
	  lib/WordNet/Similarity/jcn.pm $(INST_MAN3DIR)/WordNet::Similarity::jcn.$(MAN3EXT) \
	  lib/WordNet/Similarity/FrequencyCounter.pm $(INST_MAN3DIR)/WordNet::Similarity::FrequencyCounter.$(MAN3EXT) \
	  lib/WordNet/Similarity/GlossFinder.pm $(INST_MAN3DIR)/WordNet::Similarity::GlossFinder.$(MAN3EXT) \
	  lib/WordNet/vectorFile.pm $(INST_MAN3DIR)/WordNet::vectorFile.$(MAN3EXT) \
	  lib/WordNet/Similarity/lch.pm $(INST_MAN3DIR)/WordNet::Similarity::lch.$(MAN3EXT) \
	  lib/WordNet/Similarity/vector.pm $(INST_MAN3DIR)/WordNet::Similarity::vector.$(MAN3EXT) \
	  lib/WordNet/Similarity/res.pm $(INST_MAN3DIR)/WordNet::Similarity::res.$(MAN3EXT) \
	  lib/WordNet/get_wn_info.pm $(INST_MAN3DIR)/WordNet::get_wn_info.$(MAN3EXT) \
	  lib/WordNet/Similarity/wup.pm $(INST_MAN3DIR)/WordNet::Similarity::wup.$(MAN3EXT) 




# --- MakeMaker processPL section:

all :: $(INST_LIB)/WordNet/synsetdepths.dat
	$(NOECHO) $(NOOP)

$(INST_LIB)/WordNet/synsetdepths.dat :: build/Depthfiles.PL pm_to_blib
	$(PERLRUNINST) build/Depthfiles.PL $(INST_LIB)/WordNet/synsetdepths.dat

all :: $(INST_LIB)/WordNet/ic-semcor.dat
	$(NOECHO) $(NOOP)

$(INST_LIB)/WordNet/ic-semcor.dat :: build/Infocontent.PL pm_to_blib
	$(PERLRUNINST) build/Infocontent.PL $(INST_LIB)/WordNet/ic-semcor.dat


# --- MakeMaker installbin section:

EXE_FILES = utils/BNCFreq.pl utils/brownFreq.pl utils/compounds.pl utils/rawtextFreq.pl utils/semCorRawFreq.pl utils/semCorFreq.pl utils/similarity.pl utils/treebankFreq.pl utils/wordVectors.pl utils/wnDepths.pl utils/similarity_server.pl

pure_all :: $(INST_SCRIPT)/rawtextFreq.pl $(INST_SCRIPT)/BNCFreq.pl $(INST_SCRIPT)/similarity.pl $(INST_SCRIPT)/wordVectors.pl $(INST_SCRIPT)/compounds.pl $(INST_SCRIPT)/semCorRawFreq.pl $(INST_SCRIPT)/brownFreq.pl $(INST_SCRIPT)/similarity_server.pl $(INST_SCRIPT)/treebankFreq.pl $(INST_SCRIPT)/wnDepths.pl $(INST_SCRIPT)/semCorFreq.pl
	$(NOECHO) $(NOOP)

realclean ::
	$(RM_F) \
	  $(INST_SCRIPT)/rawtextFreq.pl $(INST_SCRIPT)/BNCFreq.pl \
	  $(INST_SCRIPT)/similarity.pl $(INST_SCRIPT)/wordVectors.pl \
	  $(INST_SCRIPT)/compounds.pl $(INST_SCRIPT)/semCorRawFreq.pl \
	  $(INST_SCRIPT)/brownFreq.pl $(INST_SCRIPT)/similarity_server.pl \
	  $(INST_SCRIPT)/treebankFreq.pl $(INST_SCRIPT)/wnDepths.pl \
	  $(INST_SCRIPT)/semCorFreq.pl 

$(INST_SCRIPT)/rawtextFreq.pl : utils/rawtextFreq.pl $(FIRST_MAKEFILE) $(INST_SCRIPT)$(DFSEP).exists $(INST_BIN)$(DFSEP).exists
	$(NOECHO) $(RM_F) $(INST_SCRIPT)/rawtextFreq.pl
	$(CP) utils/rawtextFreq.pl $(INST_SCRIPT)/rawtextFreq.pl
	$(FIXIN) $(INST_SCRIPT)/rawtextFreq.pl
	-$(NOECHO) $(CHMOD) $(PERM_RWX) $(INST_SCRIPT)/rawtextFreq.pl

$(INST_SCRIPT)/BNCFreq.pl : utils/BNCFreq.pl $(FIRST_MAKEFILE) $(INST_SCRIPT)$(DFSEP).exists $(INST_BIN)$(DFSEP).exists
	$(NOECHO) $(RM_F) $(INST_SCRIPT)/BNCFreq.pl
	$(CP) utils/BNCFreq.pl $(INST_SCRIPT)/BNCFreq.pl
	$(FIXIN) $(INST_SCRIPT)/BNCFreq.pl
	-$(NOECHO) $(CHMOD) $(PERM_RWX) $(INST_SCRIPT)/BNCFreq.pl

$(INST_SCRIPT)/similarity.pl : utils/similarity.pl $(FIRST_MAKEFILE) $(INST_SCRIPT)$(DFSEP).exists $(INST_BIN)$(DFSEP).exists
	$(NOECHO) $(RM_F) $(INST_SCRIPT)/similarity.pl
	$(CP) utils/similarity.pl $(INST_SCRIPT)/similarity.pl
	$(FIXIN) $(INST_SCRIPT)/similarity.pl
	-$(NOECHO) $(CHMOD) $(PERM_RWX) $(INST_SCRIPT)/similarity.pl

$(INST_SCRIPT)/wordVectors.pl : utils/wordVectors.pl $(FIRST_MAKEFILE) $(INST_SCRIPT)$(DFSEP).exists $(INST_BIN)$(DFSEP).exists
	$(NOECHO) $(RM_F) $(INST_SCRIPT)/wordVectors.pl
	$(CP) utils/wordVectors.pl $(INST_SCRIPT)/wordVectors.pl
	$(FIXIN) $(INST_SCRIPT)/wordVectors.pl
	-$(NOECHO) $(CHMOD) $(PERM_RWX) $(INST_SCRIPT)/wordVectors.pl

$(INST_SCRIPT)/compounds.pl : utils/compounds.pl $(FIRST_MAKEFILE) $(INST_SCRIPT)$(DFSEP).exists $(INST_BIN)$(DFSEP).exists
	$(NOECHO) $(RM_F) $(INST_SCRIPT)/compounds.pl
	$(CP) utils/compounds.pl $(INST_SCRIPT)/compounds.pl
	$(FIXIN) $(INST_SCRIPT)/compounds.pl
	-$(NOECHO) $(CHMOD) $(PERM_RWX) $(INST_SCRIPT)/compounds.pl

$(INST_SCRIPT)/semCorRawFreq.pl : utils/semCorRawFreq.pl $(FIRST_MAKEFILE) $(INST_SCRIPT)$(DFSEP).exists $(INST_BIN)$(DFSEP).exists
	$(NOECHO) $(RM_F) $(INST_SCRIPT)/semCorRawFreq.pl
	$(CP) utils/semCorRawFreq.pl $(INST_SCRIPT)/semCorRawFreq.pl
	$(FIXIN) $(INST_SCRIPT)/semCorRawFreq.pl
	-$(NOECHO) $(CHMOD) $(PERM_RWX) $(INST_SCRIPT)/semCorRawFreq.pl

$(INST_SCRIPT)/brownFreq.pl : utils/brownFreq.pl $(FIRST_MAKEFILE) $(INST_SCRIPT)$(DFSEP).exists $(INST_BIN)$(DFSEP).exists
	$(NOECHO) $(RM_F) $(INST_SCRIPT)/brownFreq.pl
	$(CP) utils/brownFreq.pl $(INST_SCRIPT)/brownFreq.pl
	$(FIXIN) $(INST_SCRIPT)/brownFreq.pl
	-$(NOECHO) $(CHMOD) $(PERM_RWX) $(INST_SCRIPT)/brownFreq.pl

$(INST_SCRIPT)/similarity_server.pl : utils/similarity_server.pl $(FIRST_MAKEFILE) $(INST_SCRIPT)$(DFSEP).exists $(INST_BIN)$(DFSEP).exists
	$(NOECHO) $(RM_F) $(INST_SCRIPT)/similarity_server.pl
	$(CP) utils/similarity_server.pl $(INST_SCRIPT)/similarity_server.pl
	$(FIXIN) $(INST_SCRIPT)/similarity_server.pl
	-$(NOECHO) $(CHMOD) $(PERM_RWX) $(INST_SCRIPT)/similarity_server.pl

$(INST_SCRIPT)/treebankFreq.pl : utils/treebankFreq.pl $(FIRST_MAKEFILE) $(INST_SCRIPT)$(DFSEP).exists $(INST_BIN)$(DFSEP).exists
	$(NOECHO) $(RM_F) $(INST_SCRIPT)/treebankFreq.pl
	$(CP) utils/treebankFreq.pl $(INST_SCRIPT)/treebankFreq.pl
	$(FIXIN) $(INST_SCRIPT)/treebankFreq.pl
	-$(NOECHO) $(CHMOD) $(PERM_RWX) $(INST_SCRIPT)/treebankFreq.pl

$(INST_SCRIPT)/wnDepths.pl : utils/wnDepths.pl $(FIRST_MAKEFILE) $(INST_SCRIPT)$(DFSEP).exists $(INST_BIN)$(DFSEP).exists
	$(NOECHO) $(RM_F) $(INST_SCRIPT)/wnDepths.pl
	$(CP) utils/wnDepths.pl $(INST_SCRIPT)/wnDepths.pl
	$(FIXIN) $(INST_SCRIPT)/wnDepths.pl
	-$(NOECHO) $(CHMOD) $(PERM_RWX) $(INST_SCRIPT)/wnDepths.pl

$(INST_SCRIPT)/semCorFreq.pl : utils/semCorFreq.pl $(FIRST_MAKEFILE) $(INST_SCRIPT)$(DFSEP).exists $(INST_BIN)$(DFSEP).exists
	$(NOECHO) $(RM_F) $(INST_SCRIPT)/semCorFreq.pl
	$(CP) utils/semCorFreq.pl $(INST_SCRIPT)/semCorFreq.pl
	$(FIXIN) $(INST_SCRIPT)/semCorFreq.pl
	-$(NOECHO) $(CHMOD) $(PERM_RWX) $(INST_SCRIPT)/semCorFreq.pl



# --- MakeMaker subdirs section:

# none

# --- MakeMaker clean_subdirs section:
clean_subdirs :
	$(NOECHO) $(NOOP)


# --- MakeMaker clean section:

# Delete temporary files but do not touch installed files. We don't delete
# the Makefile here so a later make realclean still has a makefile to use.

clean :: clean_subdirs
	- $(RM_F) \
	  *$(LIB_EXT) core \
	  core.[0-9] $(INST_ARCHAUTODIR)/extralibs.all \
	  core.[0-9][0-9] $(BASEEXT).bso \
	  pm_to_blib.ts core.[0-9][0-9][0-9][0-9] \
	  MYMETA.yml $(BASEEXT).x \
	  $(BOOTSTRAP) perl$(EXE_EXT) \
	  tmon.out *$(OBJ_EXT) \
	  pm_to_blib $(INST_ARCHAUTODIR)/extralibs.ld \
	  blibdirs.ts core.[0-9][0-9][0-9][0-9][0-9] \
	  *perl.core core.*perl.*.? \
	  $(MAKE_APERL_FILE) perl \
	  $(BASEEXT).def core.[0-9][0-9][0-9] \
	  mon.out lib$(BASEEXT).def \
	  perlmain.c perl.exe \
	  so_locations $(BASEEXT).exp 
	- $(RM_RF) \
	  blib 
	- $(MV) $(FIRST_MAKEFILE) $(MAKEFILE_OLD) $(DEV_NULL)


# --- MakeMaker realclean_subdirs section:
realclean_subdirs :
	$(NOECHO) $(NOOP)


# --- MakeMaker realclean section:
# Delete temporary files (via clean) and also delete dist files
realclean purge ::  clean realclean_subdirs
	- $(RM_F) \
	  $(MAKEFILE_OLD) $(FIRST_MAKEFILE) 
	- $(RM_RF) \
	  $(DISTVNAME) build/wnpath.txt 


# --- MakeMaker metafile section:
metafile :
	$(NOECHO) $(NOOP)


# --- MakeMaker signature section:
signature :
	cpansign -s


# --- MakeMaker dist_basics section:
distclean :: realclean distcheck
	$(NOECHO) $(NOOP)

distcheck :
	$(PERLRUN) "-MExtUtils::Manifest=fullcheck" -e fullcheck

skipcheck :
	$(PERLRUN) "-MExtUtils::Manifest=skipcheck" -e skipcheck

manifest :
	$(PERLRUN) "-MExtUtils::Manifest=mkmanifest" -e mkmanifest

veryclean : realclean
	$(RM_F) *~ */*~ *.orig */*.orig *.bak */*.bak *.old */*.old 



# --- MakeMaker dist_core section:

dist : $(DIST_DEFAULT) $(FIRST_MAKEFILE)
	$(NOECHO) $(ABSPERLRUN) -l -e 'print '\''Warning: Makefile possibly out of date with $(VERSION_FROM)'\''' \
	  -e '    if -e '\''$(VERSION_FROM)'\'' and -M '\''$(VERSION_FROM)'\'' < -M '\''$(FIRST_MAKEFILE)'\'';' --

tardist : $(DISTVNAME).tar$(SUFFIX)
	$(NOECHO) $(NOOP)

uutardist : $(DISTVNAME).tar$(SUFFIX)
	uuencode $(DISTVNAME).tar$(SUFFIX) $(DISTVNAME).tar$(SUFFIX) > $(DISTVNAME).tar$(SUFFIX)_uu

$(DISTVNAME).tar$(SUFFIX) : distdir
	$(PREOP)
	$(TO_UNIX)
	$(TAR) $(TARFLAGS) $(DISTVNAME).tar $(DISTVNAME)
	$(RM_RF) $(DISTVNAME)
	$(COMPRESS) $(DISTVNAME).tar
	$(POSTOP)

zipdist : $(DISTVNAME).zip
	$(NOECHO) $(NOOP)

$(DISTVNAME).zip : distdir
	$(PREOP)
	$(ZIP) $(ZIPFLAGS) $(DISTVNAME).zip $(DISTVNAME)
	$(RM_RF) $(DISTVNAME)
	$(POSTOP)

shdist : distdir
	$(PREOP)
	$(SHAR) $(DISTVNAME) > $(DISTVNAME).shar
	$(RM_RF) $(DISTVNAME)
	$(POSTOP)


# --- MakeMaker distdir section:
create_distdir :
	$(RM_RF) $(DISTVNAME)
	$(PERLRUN) "-MExtUtils::Manifest=manicopy,maniread" \
		-e "manicopy(maniread(),'$(DISTVNAME)', '$(DIST_CP)');"

distdir : create_distdir  
	$(NOECHO) $(NOOP)



# --- MakeMaker dist_test section:
disttest : distdir
	cd $(DISTVNAME) && $(ABSPERLRUN) Makefile.PL 
	cd $(DISTVNAME) && $(MAKE) $(PASTHRU)
	cd $(DISTVNAME) && $(MAKE) test $(PASTHRU)



# --- MakeMaker dist_ci section:

ci :
	$(PERLRUN) "-MExtUtils::Manifest=maniread" \
	  -e "@all = keys %{ maniread() };" \
	  -e "print(qq{Executing $(CI) @all\n}); system(qq{$(CI) @all});" \
	  -e "print(qq{Executing $(RCS_LABEL) ...\n}); system(qq{$(RCS_LABEL) @all});"


# --- MakeMaker distmeta section:
distmeta : create_distdir metafile
	$(NOECHO) cd $(DISTVNAME) && $(ABSPERLRUN) -MExtUtils::Manifest=maniadd -e 'eval { maniadd({q{META.yml} => q{Module meta-data (added by MakeMaker)}}) } ' \
	  -e '    or print "Could not add META.yml to MANIFEST: $${'\''@'\''}\n"' --



# --- MakeMaker distsignature section:
distsignature : create_distdir
	$(NOECHO) cd $(DISTVNAME) && $(ABSPERLRUN) -MExtUtils::Manifest=maniadd -e 'eval { maniadd({q{SIGNATURE} => q{Public-key signature (added by MakeMaker)}}) } ' \
	  -e '    or print "Could not add SIGNATURE to MANIFEST: $${'\''@'\''}\n"' --
	$(NOECHO) cd $(DISTVNAME) && $(TOUCH) SIGNATURE
	cd $(DISTVNAME) && cpansign -s



# --- MakeMaker install section:

install :: pure_install doc_install
	$(NOECHO) $(NOOP)

install_perl :: pure_perl_install doc_perl_install
	$(NOECHO) $(NOOP)

install_site :: pure_site_install doc_site_install
	$(NOECHO) $(NOOP)

install_vendor :: pure_vendor_install doc_vendor_install
	$(NOECHO) $(NOOP)

pure_install :: pure_$(INSTALLDIRS)_install
	$(NOECHO) $(NOOP)

doc_install :: doc_$(INSTALLDIRS)_install
	$(NOECHO) $(NOOP)

pure__install : pure_site_install
	$(NOECHO) $(ECHO) INSTALLDIRS not defined, defaulting to INSTALLDIRS=site

doc__install : doc_site_install
	$(NOECHO) $(ECHO) INSTALLDIRS not defined, defaulting to INSTALLDIRS=site

pure_perl_install :: all
	$(NOECHO) umask 022; $(MOD_INSTALL) \
		$(INST_LIB) $(DESTINSTALLPRIVLIB) \
		$(INST_ARCHLIB) $(DESTINSTALLARCHLIB) \
		$(INST_BIN) $(DESTINSTALLBIN) \
		$(INST_SCRIPT) $(DESTINSTALLSCRIPT) \
		$(INST_MAN1DIR) $(DESTINSTALLMAN1DIR) \
		$(INST_MAN3DIR) $(DESTINSTALLMAN3DIR)
	$(NOECHO) $(WARN_IF_OLD_PACKLIST) \
		$(SITEARCHEXP)/auto/$(FULLEXT)


pure_site_install :: all
	$(NOECHO) umask 02; $(MOD_INSTALL) \
		read $(SITEARCHEXP)/auto/$(FULLEXT)/.packlist \
		write $(DESTINSTALLSITEARCH)/auto/$(FULLEXT)/.packlist \
		$(INST_LIB) $(DESTINSTALLSITELIB) \
		$(INST_ARCHLIB) $(DESTINSTALLSITEARCH) \
		$(INST_BIN) $(DESTINSTALLSITEBIN) \
		$(INST_SCRIPT) $(DESTINSTALLSITESCRIPT) \
		$(INST_MAN1DIR) $(DESTINSTALLSITEMAN1DIR) \
		$(INST_MAN3DIR) $(DESTINSTALLSITEMAN3DIR)
	$(NOECHO) $(WARN_IF_OLD_PACKLIST) \
		$(PERL_ARCHLIB)/auto/$(FULLEXT)

pure_vendor_install :: all
	$(NOECHO) umask 022; $(MOD_INSTALL) \
		$(INST_LIB) $(DESTINSTALLVENDORLIB) \
		$(INST_ARCHLIB) $(DESTINSTALLVENDORARCH) \
		$(INST_BIN) $(DESTINSTALLVENDORBIN) \
		$(INST_SCRIPT) $(DESTINSTALLVENDORSCRIPT) \
		$(INST_MAN1DIR) $(DESTINSTALLVENDORMAN1DIR) \
		$(INST_MAN3DIR) $(DESTINSTALLVENDORMAN3DIR)

doc_perl_install :: all

doc_site_install :: all
	$(NOECHO) $(ECHO) Appending installation info to $(DESTINSTALLSITEARCH)/perllocal.pod
	-$(NOECHO) umask 02; $(MKPATH) $(DESTINSTALLSITEARCH)
	-$(NOECHO) umask 02; $(DOC_INSTALL) \
		"Module" "$(NAME)" \
		"installed into" "$(INSTALLSITELIB)" \
		LINKTYPE "$(LINKTYPE)" \
		VERSION "$(VERSION)" \
		EXE_FILES "$(EXE_FILES)" \
		>> $(DESTINSTALLSITEARCH)/perllocal.pod

doc_vendor_install :: all


uninstall :: uninstall_from_$(INSTALLDIRS)dirs
	$(NOECHO) $(NOOP)

uninstall_from_perldirs ::

uninstall_from_sitedirs ::
	$(NOECHO) $(UNINSTALL) $(SITEARCHEXP)/auto/$(FULLEXT)/.packlist

uninstall_from_vendordirs ::



# --- MakeMaker force section:
# Phony target to force checking subdirectories.
FORCE :
	$(NOECHO) $(NOOP)


# --- MakeMaker perldepend section:


# --- MakeMaker makefile section:
# We take a very conservative approach here, but it's worth it.
# We move Makefile to Makefile.old here to avoid gnu make looping.
$(FIRST_MAKEFILE) : Makefile.PL $(CONFIGDEP)
	$(NOECHO) $(ECHO) "Makefile out-of-date with respect to $?"
	$(NOECHO) $(ECHO) "Cleaning current config before rebuilding Makefile..."
	-$(NOECHO) $(RM_F) $(MAKEFILE_OLD)
	-$(NOECHO) $(MV)   $(FIRST_MAKEFILE) $(MAKEFILE_OLD)
	- $(MAKE) $(USEMAKEFILE) $(MAKEFILE_OLD) clean $(DEV_NULL)
	$(PERLRUN) Makefile.PL 
	$(NOECHO) $(ECHO) "==> Your Makefile has been rebuilt. <=="
	$(NOECHO) $(ECHO) "==> Please rerun the $(MAKE) command.  <=="
	$(FALSE)



# --- MakeMaker staticmake section:

# --- MakeMaker makeaperl section ---
MAP_TARGET    = perl
FULLPERL      = /usr/bin/perl

$(MAP_TARGET) :: static $(MAKE_APERL_FILE)
	$(MAKE) $(USEMAKEFILE) $(MAKE_APERL_FILE) $@

$(MAKE_APERL_FILE) : $(FIRST_MAKEFILE) pm_to_blib
	$(NOECHO) $(ECHO) Writing \"$(MAKE_APERL_FILE)\" for this $(MAP_TARGET)
	$(NOECHO) $(PERLRUNINST) \
		Makefile.PL DIR= \
		MAKEFILE=$(MAKE_APERL_FILE) LINKTYPE=static \
		MAKEAPERL=1 NORECURS=1 CCCDLFLAGS=


# --- MakeMaker test section:

TEST_VERBOSE=0
TEST_TYPE=test_$(LINKTYPE)
TEST_FILE = test.pl
TEST_FILES = t/*.t
TESTDB_SW = -d

testdb :: testdb_$(LINKTYPE)

test :: $(TEST_TYPE) subdirs-test

subdirs-test ::
	$(NOECHO) $(NOOP)


test_dynamic :: pure_all
	PERL_DL_NONLAZY=1 $(FULLPERLRUN) "-MExtUtils::Command::MM" "-e" "test_harness($(TEST_VERBOSE), '$(INST_LIB)', '$(INST_ARCHLIB)')" $(TEST_FILES)

testdb_dynamic :: pure_all
	PERL_DL_NONLAZY=1 $(FULLPERLRUN) $(TESTDB_SW) "-I$(INST_LIB)" "-I$(INST_ARCHLIB)" $(TEST_FILE)

test_ : test_dynamic

test_static :: test_dynamic
testdb_static :: testdb_dynamic

TEST_ALL_VERBOSE=0
TEST_ALL_TYPE=test_all_$(LINKTYPE)
TEST_ALL_FILE = test_all.pl
TEST_ALL_FILES = t/*.t t/config/*.t t/utils/*.t
TEST_ALLDB_SW = -d

test_alldb :: test_alldb_$(LINKTYPE)

test_all :: $(TEST_ALL_TYPE) subdirs-test_all

subdirs-test_all ::
	$(NOECHO) $(NOOP)


test_all_dynamic :: pure_all
	PERL_DL_NONLAZY=1 $(FULLPERLRUN) "-MExtUtils::Command::MM" "-e" "test_harness($(TEST_ALL_VERBOSE), '$(INST_LIB)', '$(INST_ARCHLIB)')" $(TEST_ALL_FILES)

test_alldb_dynamic :: pure_all
	PERL_DL_NONLAZY=1 $(FULLPERLRUN) $(TEST_ALLDB_SW) "-I$(INST_LIB)" "-I$(INST_ARCHLIB)" $(TEST_ALL_FILE)

test_all_ : test_all_dynamic

test_all_static :: test_all_dynamic
test_alldb_static :: test_alldb_dynamic


# --- MakeMaker ppd section:
# Creates a PPD (Perl Package Description) for a binary distribution.
ppd :
	$(NOECHO) $(ECHO) '<SOFTPKG NAME="$(DISTNAME)" VERSION="2.05">' > $(DISTNAME).ppd
	$(NOECHO) $(ECHO) '    <ABSTRACT>Perl modules for computing measures of semantic</ABSTRACT>' >> $(DISTNAME).ppd
	$(NOECHO) $(ECHO) '    <AUTHOR>Ted Pedersen, Siddharth Patwardhan, Satanjeev Banerjee, Jason Michelizzi</AUTHOR>' >> $(DISTNAME).ppd
	$(NOECHO) $(ECHO) '    <IMPLEMENTATION>' >> $(DISTNAME).ppd
	$(NOECHO) $(ECHO) '        <REQUIRE NAME="CGI::" />' >> $(DISTNAME).ppd
	$(NOECHO) $(ECHO) '        <REQUIRE NAME="Digest::SHA1" />' >> $(DISTNAME).ppd
	$(NOECHO) $(ECHO) '        <REQUIRE NAME="File::Find" />' >> $(DISTNAME).ppd
	$(NOECHO) $(ECHO) '        <REQUIRE NAME="File::Spec" />' >> $(DISTNAME).ppd
	$(NOECHO) $(ECHO) '        <REQUIRE NAME="File::Temp" />' >> $(DISTNAME).ppd
	$(NOECHO) $(ECHO) '        <REQUIRE NAME="Getopt::Long" />' >> $(DISTNAME).ppd
	$(NOECHO) $(ECHO) '        <REQUIRE NAME="IO::" />' >> $(DISTNAME).ppd
	$(NOECHO) $(ECHO) '        <REQUIRE NAME="Text::Similarity" VERSION="0.02" />' >> $(DISTNAME).ppd
	$(NOECHO) $(ECHO) '        <REQUIRE NAME="WordNet::QueryData" VERSION="1.4" />' >> $(DISTNAME).ppd
	$(NOECHO) $(ECHO) '        <ARCHITECTURE NAME="i686-linux-gnu-thread-multi-64int-5.14" />' >> $(DISTNAME).ppd
	$(NOECHO) $(ECHO) '        <CODEBASE HREF="" />' >> $(DISTNAME).ppd
	$(NOECHO) $(ECHO) '    </IMPLEMENTATION>' >> $(DISTNAME).ppd
	$(NOECHO) $(ECHO) '</SOFTPKG>' >> $(DISTNAME).ppd


# --- MakeMaker pm_to_blib section:

pm_to_blib : $(FIRST_MAKEFILE) $(TO_INST_PM)
	$(NOECHO) $(ABSPERLRUN) -MExtUtils::Install -e 'pm_to_blib({@ARGV}, '\''$(INST_LIB)/auto'\'', q[$(PM_FILTER)], '\''$(PERM_DIR)'\'')' -- \
	  lib/WordNet/Similarity/vector_pairs.pm blib/lib/WordNet/Similarity/vector_pairs.pm \
	  lib/WordNet/Similarity.pm blib/lib/WordNet/Similarity.pm \
	  lib/WordNet/lesk-relation.dat blib/lib/WordNet/lesk-relation.dat \
	  lib/WordNet/Similarity/hso.pm blib/lib/WordNet/Similarity/hso.pm \
	  lib/WordNet/wordvectors.dat blib/lib/WordNet/wordvectors.dat \
	  lib/WordNet/Similarity/random.pm blib/lib/WordNet/Similarity/random.pm \
	  lib/WordNet/Tools.pm blib/lib/WordNet/Tools.pm \
	  lib/WordNet/Similarity/PathFinder.pm blib/lib/WordNet/Similarity/PathFinder.pm \
	  lib/WordNet/Similarity/lesk.pm blib/lib/WordNet/Similarity/lesk.pm \
	  lib/WordNet/Similarity/DepthFinder.pm blib/lib/WordNet/Similarity/DepthFinder.pm \
	  lib/WordNet/Similarity/lin.pm blib/lib/WordNet/Similarity/lin.pm \
	  lib/WordNet/Similarity/ICFinder.pm blib/lib/WordNet/Similarity/ICFinder.pm \
	  lib/WordNet/Similarity/path.pm blib/lib/WordNet/Similarity/path.pm \
	  lib/WordNet/stem.pm blib/lib/WordNet/stem.pm \
	  lib/WordNet/Similarity/jcn.pm blib/lib/WordNet/Similarity/jcn.pm \
	  lib/WordNet/Similarity/FrequencyCounter.pm blib/lib/WordNet/Similarity/FrequencyCounter.pm \
	  lib/WordNet/Similarity/GlossFinder.pm blib/lib/WordNet/Similarity/GlossFinder.pm \
	  lib/WordNet/vectorFile.pm blib/lib/WordNet/vectorFile.pm \
	  lib/WordNet/Similarity/lch.pm blib/lib/WordNet/Similarity/lch.pm \
	  lib/WordNet/Similarity/vector.pm blib/lib/WordNet/Similarity/vector.pm \
	  lib/WordNet/vector-pairs-relation.dat blib/lib/WordNet/vector-pairs-relation.dat \
	  lib/WordNet/Similarity/res.pm blib/lib/WordNet/Similarity/res.pm \
	  lib/WordNet/vector-relation.dat blib/lib/WordNet/vector-relation.dat \
	  lib/WordNet/get_wn_info.pm blib/lib/WordNet/get_wn_info.pm \
	  lib/WordNet/Similarity/wup.pm blib/lib/WordNet/Similarity/wup.pm 
	$(NOECHO) $(TOUCH) pm_to_blib


# --- MakeMaker selfdocument section:


# --- MakeMaker postamble section:


# End.
